/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant
    Soft IP Version: 1.0.0
    Thu May 31 14:51:17 2018
*******************************************************************************/
/*******************************************************************************
    Include IP core template files.
*******************************************************************************/
`include "core/lscc_multiplier.v"
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module mle_ice40up_mul16 (clk_i, clk_en_i, rst_i, data_a_i, data_b_i, result_o);
    input  clk_i;
    input  clk_en_i;
    input  rst_i;
    input  [15:0]  data_a_i;
    input  [15:0]  data_b_i;
    output  [31:0]  result_o;
    lscc_multiplier #(.USE_COEFF(0),
        .COEFF(2),
        .A_WIDTH(16),
        .B_WIDTH(16),
        .A_SIGNED("on"),
        .B_SIGNED("on"),
        .USE_IREG("off"),
        .USE_OREG("on"),
        .PIPELINES(0),
        .IMPL("DSP"))
    lscc_multiplier_inst(.clk_i(clk_i),
        .clk_en_i(clk_en_i),
        .rst_i(rst_i),
        .data_a_i(data_a_i),
        .data_b_i(data_b_i),
        .result_o(result_o));
endmodule