/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant
    Soft IP Version: 1.0.0
    Thu May 31 14:51:17 2018
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module mle_ice40up_mul16 (clk_i, clk_en_i, rst_i, data_a_i, data_b_i, result_o)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk_i;
    input  clk_en_i;
    input  rst_i;
    input  [15:0]  data_a_i;
    input  [15:0]  data_b_i;
    output  [31:0]  result_o;
endmodule