/*******************************************************************************
    Verilog netlist generated by IPGEN Radiant Software (64-bit) 1.1.0.165.1
    Soft IP Version: 1.1.0
    Fri May 03 13:47:29 2019
*******************************************************************************/
/*******************************************************************************
    Wrapper Module generated per user settings.
*******************************************************************************/
module lsc_ml_ice40_cnn (clk, resetn, o_rd_rdy, i_start, i_we, i_waddr, i_din,
    o_we, o_dout, o_cycles, o_commands, o_fc_cycles, i_debug_rdy, o_debug_vld,
    o_fill, i_fifo_empty, i_fifo_low, o_fifo_rd, i_fifo_dout, o_status)/* synthesis syn_black_box syn_declare_black_box=1 */;
    input  clk;
    input  resetn;
    output  o_rd_rdy;
    input  i_start;
    input  i_we;
    input  [15:0]  i_waddr;
    input  [15:0]  i_din;
    output  o_we;
    output  [15:0]  o_dout;
    output  [31:0]  o_cycles;
    output  [31:0]  o_commands;
    output  [31:0]  o_fc_cycles;
    input  i_debug_rdy;
    output  o_debug_vld;
    output  o_fill;
    input  i_fifo_empty;
    input  i_fifo_low;
    output  o_fifo_rd;
    input  [31:0]  i_fifo_dout;
    output  [7:0]  o_status;
endmodule